# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Simple"
license = "MIT"
licenselink = "https://github.com/mcbrineellis/mcbrineellis.com/blob/main/themes/simple/LICENSE"
description = ""
homepage = "https://mcbrineellis.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Connor McBrine-Ellis"
  homepage = "https://mcbrineellis.com"

# If porting an existing theme
[original]
  name = "Simple"
  homepage = "https://github.com/hugomd/blog/tree/develop/themes/simple"
  repo = ""
